import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 34,
    paddingBottom: 12,
    flexGrow: 1,
  },
  pageTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 4,
    marginBottom: 14,
    textDecorationLine: 'none',
  },
  chartCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingTop: 22,
    paddingBottom: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 0.04,
  },
  chartWrap: {
    alignItems: 'center',
    paddingTop: 4,
  },
  chartSvg: {
    alignSelf: 'center',
  },
  emptyOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
  },
  // 블러 색깔 표시
  grayOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(83, 86, 93, 0.22)',
  },
  emptyContent: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  emptyStateCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    overflow: 'hidden',
    width: '100%',
    maxWidth: 320,
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 0.04,
  },
  emptyStateHeader: {
  position: 'relative',
  overflow: 'hidden',
  alignItems: 'center',
  paddingTop: 24,
  paddingBottom: 10,
},

  emptyStateBody: {
    alignItems: 'center',
    paddingHorizontal: 26,
    paddingTop: 18,
    paddingBottom: 24,
  },
  emptyStateTitle: {
    color: '#4C9E9D',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyStateMessage: {
    color: '#4B5563',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
    textAlign: 'center',
  },
  emptyStateButton: {
    alignItems: 'center',
    backgroundColor: '#5F9F9D',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    marginTop: 18,
    paddingHorizontal: 22,
    width: 138,
  },
  emptyStateButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    marginTop: 4,
    flexWrap: 'wrap',
    transform: [{translateY: -16}],
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendText: {
    color: '#6B7280',
    fontSize: 11,
  },
  chartCaption: {
    color: '#9AA7B8',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    transform: [{translateY: -12}],
  },
  // 평균 변화량 차트 스타일
  trendCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    marginTop: 12,
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 0.04,
  },
  trendHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  trendHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  trendTitle: {
    color: '#7A8497',
    fontSize: 12,
    fontWeight: '700',
  },
  trendValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 4,
    flexWrap: 'wrap',
  },
  trendValue: {
    color: '#111827',
    fontSize: 30,
    fontWeight: '800',
  },
  trendBadge: {
    backgroundColor: '#EAF8FA',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  trendBadgeText: {
    color: '#3AA7C0',
    fontSize: 11,
    fontWeight: '700',
  },
  trendSubtitle: {
    color: '#94A3B8',
    fontSize: 11,
    marginTop: 3,
  },
  trendSelector: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#F2F5FA',
    padding: 4,
    borderRadius: 999,
  },
  trendSelectorButton: {
    minWidth: 56,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  trendSelectorButtonActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 0.04,
  },
  trendSelectorText: {
    color: '#7A8497',
    fontSize: 11,
    fontWeight: '700',
  },
  trendSelectorTextActive: {
    color: '#4D90FF',
  },
  trendChartWrap: {
    marginTop: 12,
  },
  trendEmptyState: {
    height: 180,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trendEmptyText: {
    color: '#A6AFC4',
    fontSize: 14,
    textAlign: 'center',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 0.04,
  },
  summaryLabel: {
    color: '#7A8497',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  summaryValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  tabsWrap: {
    position: 'relative',
    marginBottom: 14,
    paddingBottom: 10,
  },
  tabs: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  tabDivider: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 1,
    backgroundColor: '#D9DDE7',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 4,
  },
  tabText: {
    color: '#111827',
    fontSize: 15,
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    bottom: -1,
    height: 2,
    backgroundColor: '#69B7BC',
    borderRadius: 99,
  },
  loadingBox: {
    paddingVertical: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listArea: {
    maxHeight: 420,
    marginBottom: 4,
  },
  listAreaEmpty: {
    minHeight: 120,
  },
  listScrollContent: {
    paddingBottom: 16,
  },
  list: {
    gap: 10,
  },
  itemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 0.04,
  },
  itemLeft: {
    flex: 1,
    minWidth: 0,
    gap: 8,
    paddingRight: 12,
  },
  itemDate: {
    color: '#111827',
    fontSize: 16,

  },
  itemBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EAF8FA',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  ThreeitemBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EBF5FF',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  itemBadgeText: {
    color: '#69B7BC',
    fontSize: 12,
  },
  ThreeitemBadgeText: {
    color: '#007AF5',
    fontSize: 12,
  },
  itemRight: {
    width: 122,
    flexShrink: 0,
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 6,
  },
  metricLine: {
    fontSize: 12,
    textAlign: 'right',
    lineHeight: 17,
  },
  metricLabel: {
    color: '#667085',
  },
  metricValue: {
    color: '#111827',
    fontWeight: '800',
  },
  emptyBox: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: '#20222D',
    fontSize: 16,
    fontWeight: '700',
  },
  emptyText: {
    color: '#A6AFC4',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },
});

export default styles;
