import { Colors } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';
import { textFont } from '@/src/constants/fonts';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.gray[25],
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 34,
    paddingBottom: 12,
    flexGrow: 1,
  },
  measurementRequiredContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 120,
  },
  pageTitle: {
    ...textFont,
    color: '#000000',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 4,
    marginBottom: 14,
    lineHeight : 32,
    textDecorationLine: 'none',
  },
  chartCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingTop: 22,
    paddingBottom: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    boxShadow: '0px 0px 16px rgba(0, 0, 0, 0.04)',
  },
  chartWrap: {
    alignItems: 'center',
    paddingTop: 4,
  },
  chartSvg: {
    alignSelf: 'center',
  },
  emptyOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
  },
  // 블러 색깔 표시
  grayOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(83, 86, 93, 0.22)',
  },
  emptyContent: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  emptyStateCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    overflow: 'hidden',
    width: '100%',
    maxWidth: 320,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    boxShadow: '0px 0px 16px rgba(0, 0, 0, 0.04)',
  },
  emptyStateHeader: {
  position: 'relative',
  overflow: 'hidden',
  alignItems: 'center',
  paddingTop: 24,
  paddingBottom: 10,
},

  emptyStateBody: {
    alignItems: 'center',
    paddingHorizontal: 26,
    paddingTop: 18,
    paddingBottom: 24,
  },
  emptyStateTitle: {
    ...textFont,
    color: '#4C9E9D',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyStateMessage: {
    ...textFont,
    color: '#4B5563',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
    textAlign: 'center',
  },
  emptyStateButton: {
    alignItems: 'center',
    backgroundColor: '#5F9F9D',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    marginTop: 18,
    paddingHorizontal: 22,
    width: 138,
  },
  emptyStateButtonText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 12,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    marginTop: 4,
    flexWrap: 'wrap',
    transform: [{translateY: -16}],
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendText: {
    ...textFont,
    color: '#6B7280',
    fontSize: 11,
  },
  chartCaption: {
    ...textFont,
    color: '#9AA7B8',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    transform: [{translateY: -12}],
  },
  // 평균 변화량 차트 스타일
  pressed: {
    opacity: 0.92,
  },
  resultHeader: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    zIndex: 20,
  },
  resultTitle: {
    ...textFont,
    color: Colors.gray[800],
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  periodSelectorWrap: {
    position: 'relative',
    zIndex: 30,
  },
  periodSelectButton: {
    width: 82,
    height: 32,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E7ED',
    borderRadius: 5,
  },
  periodSelectText: {
    ...textFont,
    color: '#657085',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  periodDropdownCard: {
    position: 'absolute',
    right: 0,
    top: 38,
    width: 82,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E3E7ED',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    boxShadow: '0px 0px 16px rgba(0, 0, 0, 0.04)',
  },
  periodDropdownOption: {
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  periodDropdownOptionActive: {
    backgroundColor: '#EDFDFC',
  },
  periodDropdownOptionText: {
    ...textFont,
    color: Colors.gray[600],
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  periodDropdownOptionTextActive: {
    ...textFont,
    color: Colors.primary[500],
    fontWeight: '500',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  summaryCard: {
    flex: 1,
    minHeight: 86,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    boxShadow: '0px 0px 16px rgba(0, 0, 0, 0.04)',
  },
  summaryCardActive: {
    backgroundColor: '#EDFDFC',
    borderColor: '#7AD7D4',
  },
  summaryLabel: {
    ...textFont,
    color: '#515968',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    textAlign: 'center',
  },
  summaryLabelActive: {
    color: '#20797E',
  },
  summaryValue: {
    ...textFont,
    color: '#25272D',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    textAlign: 'center',
  },
  summaryValueActive: {
    ...textFont,
    color: '#20797E',
    fontWeight: '700',
    textAlign: 'center',
  },
  screenLoadingBox: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  gap: 12,
},

screenLoadingText: {
  color: '#6B7280',
  fontFamily: 'PretendardVariable',
  fontSize: 14,
  fontWeight: '500',
},
});

export default styles;
