import { Colors } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.gray[25],
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 34,
    paddingBottom: 12,
    flexGrow: 1,
  },
  measurementRequiredContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 120,
  },
  pageTitle: {
    color: '#000000',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 4,
    marginBottom: 14,
    lineHeight : 32,
    textDecorationLine: 'none',
  },
  chartCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    position: 'relative',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingTop: 22,
    paddingBottom: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 0.04,
  },
  chartWrap: {
    alignItems: 'center',
    paddingTop: 4,
  },
  chartSvg: {
    alignSelf: 'center',
  },
  emptyOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
  },
  // 블러 색깔 표시
  grayOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(83, 86, 93, 0.22)',
  },
  emptyContent: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  emptyStateCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    overflow: 'hidden',
    width: '100%',
    maxWidth: 320,
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 0.04,
  },
  emptyStateHeader: {
  position: 'relative',
  overflow: 'hidden',
  alignItems: 'center',
  paddingTop: 24,
  paddingBottom: 10,
},

  emptyStateBody: {
    alignItems: 'center',
    paddingHorizontal: 26,
    paddingTop: 18,
    paddingBottom: 24,
  },
  emptyStateTitle: {
    color: '#4C9E9D',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyStateMessage: {
    color: '#4B5563',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
    textAlign: 'center',
  },
  emptyStateButton: {
    alignItems: 'center',
    backgroundColor: '#5F9F9D',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    marginTop: 18,
    paddingHorizontal: 22,
    width: 138,
  },
  emptyStateButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    marginTop: 4,
    flexWrap: 'wrap',
    transform: [{translateY: -16}],
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendText: {
    color: '#6B7280',
    fontSize: 11,
  },
  chartCaption: {
    color: '#9AA7B8',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    transform: [{translateY: -12}],
  },
  // 평균 변화량 차트 스타일
  pressed: {
    opacity: 0.92,
  },
  resultHeader: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    zIndex: 20,
  },
  resultTitle: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[800],
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  periodSelectorWrap: {
    position: 'relative',
    zIndex: 30,
  },
  periodSelectButton: {
    width: 82,
    height: 32,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E7ED',
    borderRadius: 5,
  },
  periodSelectText: {
    color: '#657085',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  periodDropdownCard: {
    position: 'absolute',
    right: 0,
    top: 38,
    width: 82,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E3E7ED',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 0.04,
  },
  periodDropdownOption: {
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  periodDropdownOptionActive: {
    backgroundColor: '#EDFDFC',
  },
  periodDropdownOptionText: {
    color: Colors.gray[600],
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
  },
  periodDropdownOptionTextActive: {
    color: Colors.primary[500],
    fontWeight: '500',
  },
  trendCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginTop: 8,
    padding: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0.04,
  },
  trendHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  trendHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  trendSummary: {
    gap: 6,
  },
  trendTitle: {
    fontFamily: 'PretendardVariable',
    color: '#25272D',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
  },
  trendValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trendValue: {
    fontFamily: 'PretendardVariable',
    color: '#25272D',
    fontSize: 28,
    lineHeight: 38,
    fontWeight: '700',
  },
  trendBadge: {
    backgroundColor: '#EDFDFC',
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  trendBadgeText: {
    fontFamily: 'PretendardVariable',
    color: '#20797E',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500',
  },
  trendSubtitle: {
    color: '#94A3B8',
    fontSize: 11,
    marginTop: 3,
  },
  trendSelector: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#F2F5FA',
    padding: 4,
    borderRadius: 999,
  },
  trendSelectorButton: {
    minWidth: 56,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  trendSelectorButtonActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 0.04,
  },
  trendSelectorText: {
    color: '#7A8497',
    fontSize: 11,
    fontWeight: '700',
  },
  trendSelectorTextActive: {
    color: '#4D90FF',
  },
  trendChartWrap: {
    width: '100%',
    height: 120,
    overflow: 'hidden',
  },
  trendLegend: {
    gap: 4,
    paddingTop: 2,
  },
  trendLegendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  trendLegendLine: {
    width: 30,
    height: 1,
    borderStyle: 'dashed',
    borderTopWidth: 1,
  },
  trendLegendDanger: {
    borderTopColor: '#FF4B3C',
  },
  trendLegendWarning: {
    borderTopColor: '#FABE00',
  },
  trendLegendNormal: {
    borderTopColor: '#2C9696',
  },
  trendLegendText: {
    minWidth: 22,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '400',
    textAlign: 'right',
  },
  trendLegendDangerText: {
    color: '#FF4B3C',
  },
  trendLegendWarningText: {
    color: '#FABE00',
  },
  trendLegendNormalText: {
    color: '#2C9696',
  },
  trendXAxis: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trendXAxisText: {
    color: '#97A2B9',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400',
  },
  trendEmptyState: {
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trendEmptyText: {
    color: '#A6AFC4',
    fontSize: 14,
    textAlign: 'center',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  summaryCard: {
    flex: 1,
    minHeight: 86,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0.04,
  },
  summaryCardActive: {
    backgroundColor: '#EDFDFC',
    borderColor: '#7AD7D4',
  },
  summaryLabel: {
    fontFamily: 'PretendardVariable',
    color: '#515968',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    textAlign: 'center',
  },
  summaryLabelActive: {
    color: '#20797E',
  },
  summaryValue: {
    fontFamily: 'PretendardVariable',
    color: '#25272D',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    textAlign: 'center',
  },
  summaryValueActive: {
    color: '#20797E',
    fontWeight: '700',
    textAlign: 'center',
  },
  aiDoctorCard: {
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 19,
    gap: 13,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0.04,
  },
  aiDoctorTitle: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[900],
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  aiRiskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  aiRiskIconBox: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  aiRiskTextWrap: {
    gap: 2,
  },
  aiRiskTitle: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[900],
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '400',
  },
  aiRiskLabel: {
    fontFamily: 'PretendardVariable',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  aiRiskLabelNormal: {
    color: Colors.mint[600],
  },
  aiRiskLabelModerate: {
    color: '#D2A31D',
  },
  aiRiskLabelSevere: {
    color: '#EB5858',
  },
  aiOpinionGroup: {
    alignSelf: 'stretch',
  },
  aiOpinionSection: {
    alignSelf: 'stretch',
    gap: 13,
    paddingVertical: 13,
    borderTopWidth: 1,
    borderColor: '#97A2B9',
    borderStyle: 'solid',
    overflow: 'hidden',
  },
  aiOpinionSectionLast: {
    borderBottomWidth: 1,
  },
  aiOpinionHeading: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[900],
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  aiOpinionBody: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[900],
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '400',
  },
  aiExerciseBlock: {
    gap: 12,
  },
  aiExerciseTitle: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[900],
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  aiExerciseList: {
    gap: 16,
  },
  aiExerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  aiExerciseThumb: {
    width: 89,
    height: 68,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#000000',
    overflow: 'hidden',
  },
  aiExerciseTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  aiExerciseName: {
    fontFamily: 'PretendardVariable',
    color: '#25272D',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  aiExerciseDetail: {
    fontFamily: 'PretendardVariable',
    color: Colors.gray[500],
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '400',
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  tabsWrap: {
    position: 'relative',
    marginBottom: 14,
    paddingBottom: 10,
  },
  tabs: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  tabDivider: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 1,
    backgroundColor: '#D9DDE7',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 4,
  },
  tabText: {
    color: '#111827',
    fontSize: 15,
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    bottom: -1,
    height: 2,
    backgroundColor: '#69B7BC',
    borderRadius: 99,
  },
  loadingBox: {
    paddingVertical: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listArea: {
    maxHeight: 420,
    marginBottom: 4,
  },
  listAreaEmpty: {
    minHeight: 120,
  },
  listScrollContent: {
    paddingBottom: 16,
  },
  list: {
    gap: 10,
  },
  itemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 0.04,
  },
  itemLeft: {
    flex: 1,
    minWidth: 0,
    gap: 8,
    paddingRight: 12,
  },
  itemDate: {
    color: '#111827',
    fontSize: 16,

  },
  itemBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EAF8FA',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  ThreeitemBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EBF5FF',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  itemBadgeText: {
    color: '#69B7BC',
    fontSize: 12,
  },
  ThreeitemBadgeText: {
    color: '#007AF5',
    fontSize: 12,
  },
  itemRight: {
    width: 122,
    flexShrink: 0,
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 6,
  },
  metricLine: {
    fontSize: 12,
    textAlign: 'right',
    lineHeight: 17,
  },
  metricLabel: {
    color: '#667085',
  },
  metricValue: {
    color: '#111827',
    fontWeight: '800',
  },
  emptyBox: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: '#20222D',
    fontSize: 16,
    fontWeight: '700',
  },
  emptyText: {
    color: '#A6AFC4',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },
});

export default styles;
