import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F7F8FB',
  },
  page: {
    flex: 1,
    backgroundColor: '#F7F8FB',
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '500',
    color: '#47777D',
  },
  header: {
    height: 56,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7F8FB',
    zIndex: 10,
  },
  brand: {
    color: '#6ED2CE',
    fontFamily: 'MuseoModerno_700Bold',
    fontSize: 28,
    letterSpacing: -0.3,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fontWarning: {
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#FFE8E8',
    borderWidth: 1,
    borderColor: '#F7B4B4',
  },
  fontWarningText: {
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    fontWeight: '600',
    color: '#B13535',
  },
  headerIconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#EA4B57',
    borderWidth: 1.5,
    borderColor: '#F7F8FB',
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingTop: 2,
  },
  headline: {
    fontFamily: 'PretendardVariable',
    fontSize: 16,
    fontWeight: '700',
    color: '#2C2F38',
    marginBottom: 14,
  },
  measurementGroupCard: {
    backgroundColor: 'white',
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#EDF1F7',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 2,
  },
  pressed: {
    opacity: 0.92,
  },
  measurementRow: {
    minHeight: 120,
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
  },
  measurementRowDivider: {
    height: 1,
    marginHorizontal: 18,
    backgroundColor: '#EDF1F7',
  },
  measurementRowContent: {
    flex: 1,
    gap: 10,
    paddingRight: 12,
  },
  measurementTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'nowrap',
  },
  measurementTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 17,
    fontWeight: '700',
    color: '#21242C',
  },
  proBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#F6E39A',
  },
  proBadgeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 11,
    fontWeight: '700',
    color: '#B98E0E',
  },
  measurementBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 9,
    backgroundColor: '#EAF7FB',
  },
  measurementBadgeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 13,
    fontWeight: '500',
    color: 'black',
  },
  measurementIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: '#F6FAFF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  proModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 28, 36, 0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  proModalCard: {
    width: '100%',
    maxWidth: 330,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 6,
  },
  proModalHeader: {
    height: 206,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  proModalBody: {
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 6,
    paddingBottom: 24,
  },
  proModalTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '700',
    color: '#4A8E95',
    textAlign: 'center',
  },
  proModalSubtitle: {
    marginTop: 10,
    fontFamily: 'PretendardVariable',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: '#4D5564',
    textAlign: 'center',
  },
  proModalButton: {
    marginTop: 24,
    minWidth: 118,
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: '#5F9F9E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  proModalButtonText: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  sectionBlock: {
    marginTop: 20,
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '700',
    color: '#30333B',
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
  },
  infoCard: {
    flex: 1,
  },
  infoCardImageWrap: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#DFF4F4',
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCardImage: {
    width: '80%',
    height: '80%',
  },
  infoTitle: {
    marginTop: 10,
    fontFamily: 'PretendardVariable',
    fontSize: 14,
    fontWeight: '700',
    color: '#30343D',
  },
  infoSubtitle: {
    marginTop: 2,
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    fontWeight: '500',
    color: '#6FAAB5',
  },
  bannerWrap: {
    width: '100%',
    marginTop : 20,
  },
  banner: {
    height: 112,
    borderRadius: 14,
    overflow: 'hidden',
  },
  bannerImage: {
    borderRadius: 14,
  },
  bannerBadge: {
    position: 'absolute',
    right: 11,
    bottom: 9,
    backgroundColor: 'rgba(255,255,255,0.20)',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  bannerBadgeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 10,
    fontWeight: '500',
    color: '#F5F7FA',
  },
  contentSlot: {
    height: 4,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingHorizontal: 18,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 18,
  },
  bottomTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  bottomTabLabel: {
    fontFamily: 'PretendardVariable',
    fontSize: 11,
    fontWeight: '500',
    color: '#B7BECC',
  },
  bottomTabLabelActive: {
    color: '#5E9F9E',
  },
    // 횡으로 스크롤 되는 운동 영상 표시(수정 예정)
  exerciseSection: {
  marginTop: 18,
},

exerciseSectionTitle: {
  fontSize: 22,
  fontWeight: '700',
  color: '#2B2F36',
  marginBottom: 14,
},

exerciseScrollContent: {
  paddingRight: 16,
},

exerciseCard: {
  width: 150,
  marginRight: 14,
},

exerciseThumbnail: {
  width: '100%',
  height: 140,
  borderRadius: 14,
  backgroundColor: '#E5E7EB',
  marginBottom: 10,
},

exerciseTitle: {
  fontSize: 17,
  fontWeight: '600',
  color: '#2B2F36',
  marginBottom: 4,
},

exerciseSubtitle: {
  fontSize: 14,
  fontWeight: '500',
  color: '#6A8DFF',
},
});

export default styles;
