import { StyleSheet } from 'react-native';
import { Colors } from '@/src/constants/theme';
const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  page: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '500',
    color: '#47777D',
  },
  header: {
    height: 56,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F9FAFB',
    zIndex: 10,
  },
  brand: {
    color: '#22BCB7',
    fontFamily: 'MuseoModerno_700Bold',
    fontSize: 28,
    letterSpacing: -0.3,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fontWarning: {
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#FFE8E8',
    borderWidth: 1,
    borderColor: '#F7B4B4',
  },
  fontWarningText: {
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    fontWeight: '600',
    color: '#B13535',
  },
  headerIconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#EA4B57',
    borderWidth: 1.5,
    borderColor: '#F7F8FB',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  greetingBlock: {
    gap: 4,
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  greetingTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    color: '#000000',
  },
  greetingSubtitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500',
    color: '#000000',
  },
  sectionHeading: {
    fontFamily: 'PretendardVariable',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: Colors.gray[800],
    marginBottom: 14,
  },
  measurementGrid: {
    flexDirection: 'row',
    gap: 8,
    height : 180
  },
  pressed: {
    opacity: 0.92,
  },
  measurementCard: {
    height: '100%',
    padding: 12,
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  measurementCardContent: {
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    minHeight: 66,
  },
  measurementTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: '#25272D',
    textAlign: 'center',
  },
  proBadge: {
    position: 'absolute',
    left: 12,
    top: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: 6,
    height: 18,
    borderRadius: 100,
    backgroundColor: '#FFF4A3',
    zIndex: 1,
  },
  proBadgeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#DA981C',
  },
  measurementBadge: {
    maxWidth: '100%',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#EDFDFC',
    overflow: 'hidden',
  },
  measurementBadgeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    color: Colors.mint[600],
    textAlign: 'center',
  },
  measurementIconWrap: {
    width: 70,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 10,
  },
  proModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 28, 36, 0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  proModalCard: {
    width: '100%',
    maxWidth: 330,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 6,
  },
  proModalHeader: {
    height: 206,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  proModalBody: {
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 6,
    paddingBottom: 24,
  },
  proModalTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '700',
    color: '#4A8E95',
    textAlign: 'center',
  },
  proModalSubtitle: {
    marginTop: 10,
    fontFamily: 'PretendardVariable',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: '#4D5564',
    textAlign: 'center',
  },
  proModalButton: {
    marginTop: 24,
    minWidth: 118,
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: '#5F9F9E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  proModalButtonText: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  sectionBlock: {
    marginTop: 20,
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '700',
    color: '#30333B',
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
  },
  infoCard: {
    flex: 1,
  },
  infoCardImageWrap: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#DFF4F4',
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCardImage: {
    width: '80%',
    height: '80%',
  },
  infoTitle: {
    marginTop: 10,
    fontFamily: 'PretendardVariable',
    fontSize: 14,
    fontWeight: '700',
    color: '#30343D',
  },
  infoSubtitle: {
    marginTop: 2,
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    fontWeight: '500',
    color: '#6FAAB5',
  },
  bannerWrap: {
    width: '100%',
    marginTop : 16,
  },
  banner: {
    height: 112,
    borderRadius: 12,
    overflow: 'hidden',
  },
  bannerImage: {
    borderRadius: 12,
  },
  bannerBadge: {
    position: 'absolute',
    right: 11,
    bottom: 9,
    backgroundColor: 'rgba(255,255,255,0.20)',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  bannerBadgeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 10,
    fontWeight: '500',
    color: '#F5F7FA',
  },
  weeklySection: {
    marginTop: 20,
  },
  weeklyResultGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  weeklyResultCard: {
    flex: 1,
    minHeight: 86,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  weeklyResultCardActive: {
    backgroundColor: '#EDFDFC',
    borderColor: '#7AD7D4',
  },
  weeklyResultLabel: {
    fontFamily: 'PretendardVariable',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    color: '#515968',
    textAlign: 'center',
  },
  weeklyResultLabelActive: {
    color: '#20797E',
  },
  weeklyResultValue: {
    fontFamily: 'PretendardVariable',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#25272D',
  },
  weeklyResultValueActive: {
    color: '#20797E',
  },
  trendCard: {
    marginTop: 8,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  trendHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  trendSummary: {
    gap: 6,
  },
  trendCaption: {
    fontFamily: 'PretendardVariable',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
    color: Colors.gray[900],
  },
  trendValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trendAverageValue: {
    fontFamily: 'PretendardVariable',
    fontSize: 28,
    lineHeight: 38,
    fontWeight: '700',
    color: Colors.gray[900],
  },
  trendChangeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: Colors.mint[25],
  },
  trendChangeText: {
    fontFamily: 'PretendardVariable',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500',
    color: Colors.mint[600],
  },
  trendLegend: {
    gap: 4,
    paddingTop: 2,
  },
  trendLegendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  trendLegendLine: {
    width: 30,
    height: 1,
    borderStyle: 'dashed',
    borderTopWidth: 1,
  },
  trendLegendDanger: {
    borderTopColor: '#FF4B3C',
  },
  trendLegendWarning: {
    borderTopColor: '#FABE00',
  },
  trendLegendNormal: {
    borderTopColor: Colors.mint[500],
  },
  trendLegendText: {
    minWidth: 22,
    fontFamily: 'PretendardVariable',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '400',
    textAlign: 'right',
  },
  trendLegendDangerText: {
    color: '#FF4B3C',
  },
  trendLegendWarningText: {
    color: '#FABE00',
  },
  trendLegendNormalText: {
    color: Colors.mint[500],
  },
  trendChartWrap: {
    width: '100%',
    height: 120,
    overflow: 'hidden',
  },
  trendXAxis: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trendXAxisText: {
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400',
    color: Colors.gray[300],
  },
  contentSlot: {
    height: 20,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingHorizontal: 18,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 18,
  },
  bottomTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  bottomTabLabel: {
    fontFamily: 'PretendardVariable',
    fontSize: 11,
    fontWeight: '500',
    color: '#B7BECC',
  },
  bottomTabLabelActive: {
    color: '#5E9F9E',
  },
});

export default styles;
