import { StyleSheet } from 'react-native';
import { textFont } from '@/src/constants/fonts';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    overflow: 'hidden',
  },
  content: {
    flex: 1,
    overflow: 'hidden',
  },
  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    paddingHorizontal: 60,
  },
  backButton: {
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    ...textFont,
    color: '#36595E',
    fontSize: 40,
  },
  angleWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
    elevation: 100,
  },
  flatAngleAnchor: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    elevation: 100,
  },
  landscapeAngleAnchor: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    elevation: 100,
  },
  angleText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: '700',
    letterSpacing: 0,
    textShadowColor: 'rgba(0, 0, 0, 0.18)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  angleTextDark: {
    color: '#3F6268',
  },
  surface: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    zIndex: 5,
  },
  bottomBubble: {
    position: 'absolute',
    bottom: -26,
    width: 46,
    height: 46,
    borderRadius: 26,
    backgroundColor: '#7AA6FF',
    zIndex: 8,
  },
  landscapeGuideTextWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 101,
    elevation: 101,
  },
  landscapeGuideAnchor: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 101,
    elevation: 101,
  },
  landscapeGuideText: {
    ...textFont,
    color: '#4B5663',
    fontSize: 13,
    fontWeight: '500',
  },
  flatSvg: {
    position: 'absolute',
    zIndex: 10,
  },
  flatGuideTextWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 35,
    alignItems: 'center',
    zIndex: 21,
    elevation: 21,
  },
  flatGuideText: {
    ...textFont,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  bottomActions: {
    position: 'absolute',
    bottom: 25,
    zIndex: 20,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomActionSlot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomActionCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  bottomCenterSpacer: {
    width: '100%',
    height: 1,
  },
  bottomGuideText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },

  zeroButton: {
    width: '86%',
    maxWidth: 192,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  measureButton: {
    width: '86%',
    maxWidth: 192,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2C9696',
  },
  measureButtonDisabled: {
    opacity: 0.72,
  },
  zeroButtonText: {
    ...textFont,
    color: '#657085',
    fontSize: 14,
    fontWeight: '500',
  },
  measureButtonText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  unsupported: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: '#9EDAD6',
  },
  unsupportedText: {
    ...textFont,
    color: '#315A60',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 24,
  },
});

export default styles;
