import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

// 번역 데이터
const translations = {
  ko: {
    // 공통
    common: {
      save: '저장',
      saving: '저장 중...',
      cancel: '취소',
      confirm: '확인',
      close: '닫기',
      next: '다음',
      prev: '이전',
      back: '뒤로',
      loading: '로딩 중...',
      error: '오류',
      success: '성공',
    },
    // 헤더/네비게이션
    nav: {
      home: '홈',
      analysis: '분석',
      report: '리포트',
      hospital: '병원',
      shopping: '쇼핑',
      more: '마이',
    },
    // 로그인
    login: {
      title: 'Scolioscan',
      subtitle: '당신의 척추 건강을 측정합니다',
      emailPlaceholder: '이메일을 입력하세요',
      passwordPlaceholder: '비밀번호를 입력하세요',
      loginButton: '로그인',
      forgotPassword: '비밀번호 찾기',
      signup: '회원가입',
      emailRequired: '이메일을 입력해주세요.',
      passwordRequired: '비밀번호를 입력해주세요.',
      loginFailed: '로그인에 실패했습니다.',
    },
    // 온보딩
    onboarding: {
      slide1Title: '척추측만증이란?',
      slide1Content: [
        '척추측만증은 척추가 옆으로 휘는 질환으로,',
        '자세 불균형이나 어깨 높이 차이로 나타납니다.',
        '심하면 통증이나 호흡에 영향을 줄 수 있어',
        '조기 관리가 필요합니다.'
      ],
      slide2Title: '스콜리오스캔은?',
      slide2Content: [
        '휴대폰으로 척추를 스캔하여 AI가 분석하고,',
        '결과를 병원 전문가에게 전달해 ',
        '피드백을 받는 비대면 검사 서비스예요.',
        'X-ray 없이 안전하고 빠르게 ',
        '척추측만증을 확인할 수 있습니다.'
      ],
      slide3Title: '스콜리오스캔 사용법',
      slide3Content: [
        '휴대폰으로 척추를 스캔하여 AI가 분석하고,',
        '결과를 병원 전문가에게 전달해 ',
        '피드백을 받는 비대면 검사 서비스예요.',
        'X-ray 없이 안전하고 빠르게 ',
        '척추측만증을 확인할 수 있습니다.'
      ],
    },
    // 홈
    home: {
      spineCheckup: '3분만에 끝나는 척추검진',
      measurement2D: '2D 이미지 측정',
      measurement2DDesc: '카메라를 통한 간편 측정',
      measurement3D: '3D 동영상 측정',
      measurement3DDesc: '영상을 통한 정밀 측정',
      measurementDevice: '척추측만계 측정',
      measurementDeviceDesc: '기기를 통한 정확한 측정',
      whatIsScoliosis: '척추측만증이란?',
      learnScoliosis: '척추측만증 알아보기',
      howToUse: '스콜리오스캔 사용법',
      learnHowToUse: '사용법 알아보기',
      nearbyHospitals: '가까운 병원 찾기',
      preparingMeasurement: '은\n준비중이에요',
      waitPlease: '조금만 기다려주세요!',
      goHome: '홈으로 돌아가기',
    },
    // 척추측만계 온보딩
    scoliometer: {
      slide1Title: '척추측만계란?',
      slide1Content: [
        '척추측만계는 척추의 회전 각도를 측정하는',
        '전문 의료기기입니다.',
        '등의 굽은 정도를 정확하게 측정하여',
        '척추측만증 여부를 확인할 수 있습니다.'
      ],
      slide2Title: '측정 준비',
      slide2Content: [
        '편안하게 서서 상의를 벗어주세요.',
        '양팔은 자연스럽게 내려뜨려주세요.',
        '측정자가 척추측만계를 등에 대고',
        '척추 뼈를 따라 차례대로 스캔합니다.'
      ],
      slide3Title: '측정 시작',
      slide3Content: [
        '측정된 값은 인터넷을 통해',
        '서버로 자동 전송됩니다.',
        '등 상부와 허리 부위를 각각 측정하여',
        '정확한 진단 결과를 확인할 수 있습니다.'
      ],
    },
    // 분석
    analysis: {
      title: '분석',
      progressionRate: '평균 변화량',
      recentChange: '최근 변화',
      upperBack: '상부 흉추만곡',
      middleBack: '주 흉추만곡',
      thoracolumbar: '흉요추 만곡',
      lumbar: '요추 만곡',
      measurementList: '측정 목록',
      viewAll: '모두 보기',
      emptyMessage: '척추 검진을 수행해서\n분석 결과를 받아보세요',
      measurementResult: '측정 결과',
      image: '이미지',
      camera2D: '2D 카메라 촬영',
      video3D: '3D 동영상 촬영',
      scoliometerMeasurement: '척추측만계 측정',
      noRecentHistory: '최근 분석 이력이 없습니다.',
      score: '점수',
    },
    // 더보기
    more: {
      title: '마이페이지',
      profileEdit: '프로필 편집',
      subscription: '구독 서비스',
      settings: '환경 설정',
      customerCenter: '고객 센터',
      logout: '로그아웃',
    },
    // 설정
    settings: {
      title: '환경 설정',
      notificationSettings: '알림 설정',
      pushNotifications: '푸시 알림 받기',
      pushNotificationsDesc: '측정 결과 알림, 일정 등',
      emailNotifications: '이메일 알림 받기',
      emailNotificationsDesc: '주요 소식 등',
      dataBackup: '데이터 자동 백업',
      dataBackupDesc: '측정 데이터 자동 백업',
      languageSettings: '언어 설정',
      language: '언어',
      languageDesc: '앱 표시 언어',
      korean: '한국어',
      english: 'English',
      saved: '설정이 저장되었습니다.',
      saveError: '설정 저장 중 오류가 발생했습니다.',
    },
    // 프로필 편집
    profile: {
      title: '프로필 편집',
      name: '이름',
      email: '이메일',
      phone: '전화번호',
      birthDate: '생년월일',
      height: '키',
      weight: '체중',
      changeProfileImage: '프로필 사진 변경',
      password: '비밀번호',
      newPassword: '새 비밀번호 (6자 이상)',
      confirmPassword: '비밀번호 확인',
      gender: '성별',
      male: '남성',
      female: '여성',
      saved: '프로필이 저장되었습니다.',
      birthdayRequired: '생년월일을 모두 입력해주세요.',
      passwordMismatch: '새 비밀번호가 일치하지 않습니다.',
      passwordTooShort: '비밀번호는 6자 이상이어야 합니다.',
      saveError: '프로필 저장 중 오류가 발생했습니다.',
    },
    // 비밀번호 찾기
    passwordReset: {
      title: '비밀번호 찾기',
      info: '가입하신 이메일 주소와 이름을 입력해주세요.\n새로운 비밀번호를 이메일로 보내드립니다.',
      email: '이메일',
      name: '이름',
      emailPlaceholder: 'abc@nextvinetech.com',
      namePlaceholder: '이름을 입력해주세요',
      submit: '비밀번호 찾기',
      emailRequired: '이메일을 입력해주세요',
      invalidEmail: '이메일 형식이 아닙니다',
      nameRequired: '이름을 입력해주세요',
      wrongInfo: '이메일 혹은 이름을 잘못 입력하였습니다',
      success: '새로운 비밀번호가 이메일로 발송되었습니다.',
    },
    // 고객 센터
    contact: {
      title: '고객 센터',
      replyEmail: '답변 받으실 이메일',
      inquiryType: '문의 유형',
      inquiryContent: '문의 내용',
      contentPlaceholder: '문의 내용을 작성해주세요',
      submit: '문의하기',
      submitting: '전송 중...',
      types: ['구독 문의', '결제 문의', '기능 문의', '기타 문의'],
      emailRequired: '이메일을 입력해주세요.',
      contentRequired: '문의 내용을 입력해주세요.',
      success: '문의가 접수되었습니다.',
      failed: '문의 접수에 실패했습니다.',
      serverError: '서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.',
      invalidInput: '입력 정보를 확인해주세요.',
    },
    // 회원가입
    signup: {
      emailStep: '이메일을 입력해주세요',
      emailStepLine1: '이메일을',
      emailStepLine2: '입력해주세요',
      passwordStep: '비밀번호를 입력해주세요',
      passwordStepLine1: '비밀번호를',
      passwordStepLine2: '입력해주세요',
      passwordPlaceholder: '비밀번호를 입력해주세요',
      passwordHasLetterNumberSpecial: '영문자, 숫자, 특수문자 포함',
      passwordMinLength: '최소 8자 이상',
      confirmPasswordStep: '비밀번호를 한 번 더 입력해주세요',
      nameStep: '이름을 입력해주세요',
      nameStepLine1: '이름을',
      nameStepLine2: '입력해주세요',
      namePlaceholder: '홍길동',
      nameMaxLength: '최대 8자까지 입력 가능합니다',
      birthStep: '생년월일을 입력해주세요',
      birthStepLine1: '생년월일을',
      birthStepLine2: '입력해주세요',
      genderStep: '성별을 선택해주세요',
      genderStepLine1: '마지막으로',
      genderStepLine2: '성별을 알려주세요',
      continue: '계속하기',
      start: '시작하기',
      emailPlaceholder: 'abc@nextvinetech.com',
      emailRequired: '이메일을 입력해주세요',
      invalidEmail: '이메일 형식이 아닙니다',
      emailExists: '이미 가입한 이메일입니다',
      emailCheckError: '이메일 확인 중 오류가 발생했습니다',
      passwordRequired: '비밀번호를 입력해주세요',
      passwordTooShort: '비밀번호는 6자 이상이어야 합니다',
      passwordMismatch: '비밀번호가 일치하지 않습니다',
      nameRequired: '이름을 입력해주세요',
      yearPlaceholder: '년도',
      monthPlaceholder: '월',
      dayPlaceholder: '일',
      male: '남성',
      female: '여성',
      signupFailed: '회원가입에 실패했습니다.',
      stepTitleEmail: '이메일',
      stepTitlePassword: '비밀번호',
      stepTitleName: '이름',
      stepTitleBirth: '생년월일',
      stepTitleGender: '성별',
      stepTitleDefault: '회원가입',
    },
    // 사이드 메뉴
    sideMenu: {
      regularMember: '일반 회원',
      accountInfo: '계정정보',
      subscriptionSettings: '구독설정',
      settings: '환경설정',
      customerService: '고객센터',
      logout: '로그아웃',
      relatedServices: '관련 서비스',
      gymWork: '짐워크',
      spineHealth: '척추건강',
      smartShoes: '스마트슈즈',
      wristDoctor: '손목닥터',
    },
    // 마이페이지
    morePage: {
      user: '사용자',
      browseApps: '관련 앱 둘러보세요',
      gymWork: '짐워크',
      spineHealth: '척추건강',
      smartShoes: '스마트슈즈',
      wristDoctor: '손목닥터',
      imageOnly: '이미지 파일만 업로드 가능합니다.',
      imageSizeLimit: '이미지 크기는 5MB 이하여야 합니다.',
      profileImageChanged: '프로필 이미지가 변경되었습니다.',
      uploadFailed: '이미지 업로드에 실패했습니다. 다시 시도해주세요.',
    },
    // 측정 목록
    measurementList: {
      title: '측정 목록',
      newest: '최신순',
      oldest: '오래된순',
      upperBack: '등 상부',
      lumbar: '허리',
      noData: '측정 데이터가 없습니다',
      loading: '불러오는 중...',
      camera2D: '2D 카메라 촬영',
      video3D: '3D 동영상 촬영',
      scoliometerMeasure: '척추측만계 측정',
    },
    // 리포트
    report: {
      spineBalanceAnalysis: '척추 균형 분석',
      severityAnalysis: '심각도 분석',
      curvePattern: '곡선 패턴',
      doctorOpinion: '의사 소견 (최종 평가)',
      proximalThoracic: '상부 흉추만곡',
      mainThoracic: '주 흉추만곡',
      secondThoracic: '보조 흉추',
      lumbar: '요추만곡',
      pelvicTilt: '골반 기울기',
      shoulderTilt: '어깨 수평 기울기',
      myMeasurement: '나의 측정값',
      populationAvg: '인구 평균',
      koreaAvg: '한국 측만도평균',
      chartDescription: '나의 척추 균형(녹색)과 인구 평균(회색)을 비교한 차트입니다',
      triangleChartDescription: '나의 측만 각도(민트색)와 한국 평균(회색 점선, 18°)을 비교한 차트입니다. 중심에 가까울수록 정상입니다.',
      mild: '경증',
      moderate: '중등도',
      severe: '중증',
      mildRange: '경증 (10-24°)',
      moderateRange: '중등도 (25-40°)',
      severeRange: '중증 (40° 초과)',
      mainCurveAngle: '주요 만곡 각도는 {angle}°로, {severity}에 해당합니다',
      noDataTitle: '측정 데이터 없음',
      noDataDesc: '척추 측정을 먼저 진행해주세요',
      doubleThoracic: '이중 흉추 만곡',
      doubleThoracicDesc: '등 상부와 중부에 두 개의 만곡이 있으며 허리는 비교적 곧은 형태입니다',
      thoracolumbarSCurve: '흉추-요추 만곡 (S자형)',
      thoracolumbarSCurveDesc: '등과 허리에 반대 방향의 만곡이 있는 S자 형태입니다',
      singleThoracic: '단일 흉추 만곡',
      singleThoracicDesc: '주로 등 부위에 하나의 만곡이 있는 형태입니다',
      lumbarCurve: '요추 만곡',
      lumbarCurveDesc: '주로 허리 부위에 만곡이 있는 형태입니다',
      normalRange: '정상 범위',
      normalRangeDesc: '척추가 정상 범위 내에 있습니다. 꾸준한 관리를 권장합니다',
      complexCurve: '복합 만곡',
      complexCurveDesc: '여러 부위에 만곡이 있는 복합적인 형태입니다',
      riskAssessment: '위험도 평가',
      normal: '정상',
      mildRisk: '경증 위험',
      moderateRisk: '중등도 위험',
      severeRisk: '중증 위험',
      prognosis: '예후',
      braceRecommendation: '보조기 권장 사항',
      postureErgonomics: '자세 및 인체공학',
      recommendedExercises: '권장 운동',
      prognosisUnder20: '연 1회 정기 관찰을 권장합니다. 일상에서 자세를 인식하고 바른 자세를 유지해주세요.',
      prognosis20to40: '6개월 간격으로 재평가를 권장합니다. 전문의 상담을 고려해주세요.',
      prognosisOver40: '조속한 정형외과 전문의 상담을 권장합니다.',
      normalPrognosis: '현재 척추 상태가 양호합니다. 정기적인 자세 점검과 운동으로 건강을 유지하세요.',
      normalBrace: '보조기 착용이 필요하지 않습니다.',
      normalPosture: '바른 자세 습관을 유지하고, 장시간 같은 자세를 피하세요.',
      mildPrognosis: '경미한 만곡이 있으나 적절한 관리로 진행을 예방할 수 있습니다.',
      mildBrace: '보조기 착용은 필요하지 않으나, 정기 검진을 권장합니다.',
      mildPosture: '바른 자세를 유지하고, 코어 근육 강화 운동을 꾸준히 하세요.',
      moderatePrognosis: '만곡이 점진적으로 진행될 수 있어 지속적인 관리가 필요합니다.',
      moderateBrace: '교정 효과를 위해 TLSO 보조기를 하루 18-20시간 착용하세요.',
      moderatePosture: '앉거나 설 때 바른 자세를 유지하고, 허리 지지대가 있는 의자를 사용하세요.',
      severePrognosis: '전문의 상담이 필요합니다. 수술적 치료가 고려될 수 있습니다.',
      severeBrace: '전문의와 상담 후 적합한 보조기 처방을 받으세요.',
      severePosture: '무리한 활동을 피하고, 전문가의 지도 하에 재활 운동을 진행하세요.',
      exercise1Mild: '코어 강화: 플랭크',
      exercise1MildDur: '30-60초 유지, 3세트',
      exercise2Mild: '스트레칭: 고양이-소 자세',
      exercise2MildDur: '10회 반복, 2세트',
      exercise3Mild: '균형 운동: 버드독',
      exercise3MildDur: '양쪽 각 10회, 2세트',
      exercise1Moderate: '부드러운 스트레칭: 아기 자세',
      exercise1ModerateDur: '30초 유지, 5회',
      exercise2Moderate: '호흡 운동: 복식 호흡',
      exercise2ModerateDur: '5분간 천천히',
      exercise3Moderate: '가벼운 걷기',
      exercise3ModerateDur: '20-30분, 평지에서',
      exercise1Severe: '전문가 지도 하 재활 운동',
      exercise1SevereDur: '물리치료사와 상담',
      exercise2Severe: '수중 운동',
      exercise2SevereDur: '전문가 권장 시간',
      exercise3Severe: '호흡 운동',
      exercise3SevereDur: '하루 10분',
      followUpAppointment: '후속 진료 예약',
      preparingTitle: '준비중입니다',
      preparingDesc: '후속 진료 예약 기능을\n준비하고 있습니다',
      emptyStateMessage: '척추 검진을 수행해서\n분석 리포트를 확인하세요',
    },
    // 구독
    subscription: {
      title: '구독 설정',
      premiumSubscription: '프리미엄 구독',
      feature1: 'AI 기반 정밀 척추 분석',
      feature2: '무제한 측정 및 분석 리포트',
      feature3: '전문의 소견 및 조언 확인',
      feature4: '맞춤형 운동 추천 및 교정 가이드',
      monthlyPrice: '월 {price}원',
      subscribed: '구독중',
      cancelSubscription: '구독 취소',
      subscribe: '구독하기',
      nextBillingDate: '다음 결제일: {date}',
      membershipNotes: '멤버십 유의사항',
      purchaseGuide: '구매안내',
      refundGuide: '환불안내',
      note1: '결제금액은 부가세가 포함된 가격입니다',
      note2: '등록하신 결제수단으로 매월 정기결제일에 멤버십 이용 금액이 자동으로 결제됩니다.',
      note3: '멤버십은 언제든 해지할 수 있으며 해지해도 결제만료일까지 사용 가능합니다',
      cancelConfirmTitle: '구독 취소',
      cancelConfirmMessage: '정말 구독을 취소하시겠습니까?\n취소해도 결제 만료일까지는 사용할 수 있습니다.',
      cancel: '취소',
      confirm: '확인',
      notice: '알림',
      preparing: '준비중입니다.',
      subscribeSuccess: '구독이 완료되었습니다.',
      subscribeFailed: '구독에 실패했습니다.',
      cancelSuccess: '구독이 취소되었습니다.',
      cancelFailed: '구독 취소에 실패했습니다.',
      // Plan name translations
      planNames: {
        '베이직': '베이직',
        '스탠다드': '스탠다드',
        '프리미엄': '프리미엄',
      },
    },
  },
  en: {
    // Common
    common: {
      save: 'Save',
      saving: 'Saving...',
      cancel: 'Cancel',
      confirm: 'Confirm',
      close: 'Close',
      next: 'Next',
      prev: 'Previous',
      back: 'Back',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
    },
    // Header/Navigation
    nav: {
      home: 'Home',
      analysis: 'Analysis',
      report: 'Report',
      hospital: 'Hospital',
      shopping: 'Shop',
      more: 'My',
    },
    // Login
    login: {
      title: 'Scolioscan',
      subtitle: 'Measure your spine health',
      emailPlaceholder: 'Enter your email',
      passwordPlaceholder: 'Enter your password',
      loginButton: 'Login',
      forgotPassword: 'Forgot Password',
      signup: 'Sign Up',
      emailRequired: 'Please enter your email.',
      passwordRequired: 'Please enter your password.',
      loginFailed: 'Login failed.',
    },
    // Onboarding
    onboarding: {
      slide1Title: 'What is Scoliosis?',
      slide1Content: [
        'Scoliosis is a condition where the spine curves sideways,',
        'showing signs like posture imbalance or uneven shoulder height.',
        'If severe, it can affect pain or breathing,',
        'requiring early management.'
      ],
      slide2Title: 'What is Scolioscan?',
      slide2Content: [
        'Scan your spine with your phone and AI analyzes it,',
        'then the results are sent to hospital experts',
        'for feedback through a contactless examination service.',
        'You can safely and quickly check for scoliosis',
        'without X-rays.'
      ],
      slide3Title: 'How to Use Scolioscan',
      slide3Content: [
        'Scan your spine with your phone and AI analyzes it,',
        'then the results are sent to hospital experts',
        'for feedback through a contactless examination service.',
        'You can safely and quickly check for scoliosis',
        'without X-rays.'
      ],
    },
    // Home
    home: {
      spineCheckup: 'Spine Checkup in 3 Minutes',
      measurement2D: '2D Image Scan',
      measurement2DDesc: 'Simple measurement with camera',
      measurement3D: '3D Video Scan',
      measurement3DDesc: 'Precise measurement with video',
      measurementDevice: 'Scoliometer Scan',
      measurementDeviceDesc: 'Accurate measurement with device',
      whatIsScoliosis: 'What is Scoliosis?',
      learnScoliosis: 'Learn about Scoliosis',
      howToUse: 'How to Use Scolioscan',
      learnHowToUse: 'Learn how to use',
      nearbyHospitals: 'Find Nearby Hospitals',
      preparingMeasurement: ' is\nbeing prepared',
      waitPlease: 'Please wait a moment!',
      goHome: 'Go to Home',
    },
    // Scoliometer onboarding
    scoliometer: {
      slide1Title: 'What is a Scoliometer?',
      slide1Content: [
        'A scoliometer is a professional medical device',
        'that measures the rotation angle of the spine.',
        'It accurately measures the degree of back curvature',
        'to check for scoliosis.'
      ],
      slide2Title: 'Preparation',
      slide2Content: [
        'Stand comfortably and remove your top clothing.',
        'Let your arms hang naturally.',
        'The examiner will place the scoliometer on your back',
        'and scan along the spine bones sequentially.'
      ],
      slide3Title: 'Start Measurement',
      slide3Content: [
        'The measured values are automatically transmitted',
        'to the server via the internet.',
        'The upper back and lumbar areas are measured separately',
        'to confirm accurate diagnosis results.'
      ],
    },
    // Analysis
    analysis: {
      title: 'Analysis',
      progressionRate: 'Average Change',
      recentChange: 'Recent Change',
      upperBack: 'Proximal Thoracic',
      middleBack: 'Main Thoracic',
      thoracolumbar: 'Thoracolumbar',
      lumbar: 'Lumbar Curve',
      measurementList: 'Measurement List',
      viewAll: 'View All',
      emptyMessage: 'Perform a spine checkup\nto receive analysis results',
      measurementResult: 'Measurement Result',
      image: 'Image',
      camera2D: '2D Camera Scan',
      video3D: '3D Video Scan',
      scoliometerMeasurement: 'Scoliometer Scan',
      noRecentHistory: 'No recent analysis history.',
      score: 'Score',
    },
    // More
    more: {
      title: 'My Page',
      profileEdit: 'Edit Profile',
      subscription: 'Subscription',
      settings: 'Settings',
      customerCenter: 'Customer Service',
      logout: 'Logout',
    },
    // Settings
    settings: {
      title: 'Settings',
      notificationSettings: 'Notification Settings',
      pushNotifications: 'Push Notifications',
      pushNotificationsDesc: 'Measurement results, schedules, etc.',
      emailNotifications: 'Email Notifications',
      emailNotificationsDesc: 'Important news, etc.',
      dataBackup: 'Auto Data Backup',
      dataBackupDesc: 'Automatic measurement data backup',
      languageSettings: 'Language Settings',
      language: 'Language',
      languageDesc: 'App display language',
      korean: '한국어',
      english: 'English',
      saved: 'Settings saved.',
      saveError: 'Error saving settings.',
    },
    // Profile Edit
    profile: {
      title: 'Edit Profile',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      birthDate: 'Birth Date',
      height: 'Height',
      weight: 'Weight',
      changeProfileImage: 'Change Profile Picture',
      password: 'Password',
      newPassword: 'New password (min 6 chars)',
      confirmPassword: 'Confirm password',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      saved: 'Profile saved.',
      birthdayRequired: 'Please enter your complete birth date.',
      passwordMismatch: 'Passwords do not match.',
      passwordTooShort: 'Password must be at least 6 characters.',
      saveError: 'Error saving profile.',
    },
    // Password Reset
    passwordReset: {
      title: 'Find Password',
      info: 'Enter your registered email address and name.\nWe will send a new password to your email.',
      email: 'Email',
      name: 'Name',
      emailPlaceholder: 'abc@nextvinetech.com',
      namePlaceholder: 'Enter your name',
      submit: 'Find Password',
      emailRequired: 'Please enter your email',
      invalidEmail: 'Invalid email format',
      nameRequired: 'Please enter your name',
      wrongInfo: 'Email or name is incorrect',
      success: 'New password has been sent to your email.',
    },
    // Customer Service
    contact: {
      title: 'Customer Service',
      replyEmail: 'Reply Email',
      inquiryType: 'Inquiry Type',
      inquiryContent: 'Inquiry Content',
      contentPlaceholder: 'Please write your inquiry',
      submit: 'Submit',
      submitting: 'Sending...',
      types: ['Subscription', 'Payment', 'Features', 'Others'],
      emailRequired: 'Please enter your email.',
      contentRequired: 'Please enter your inquiry.',
      success: 'Inquiry has been submitted.',
      failed: 'Failed to submit inquiry.',
      serverError: 'Server error. Please try again later.',
      invalidInput: 'Please check your input.',
    },
    // Signup
    signup: {
      emailStep: 'Enter your email',
      emailStepLine1: 'Please enter',
      emailStepLine2: 'your email',
      passwordStep: 'Enter your password',
      passwordStepLine1: 'Please enter',
      passwordStepLine2: 'your password',
      passwordPlaceholder: 'Enter your password',
      passwordHasLetterNumberSpecial: 'Letters, numbers, and special characters',
      passwordMinLength: 'At least 8 characters',
      confirmPasswordStep: 'Confirm your password',
      nameStep: 'Enter your name',
      nameStepLine1: 'Please enter',
      nameStepLine2: 'your name',
      namePlaceholder: 'John Doe',
      nameMaxLength: 'Maximum 8 characters allowed',
      birthStep: 'Enter your birth date',
      birthStepLine1: 'Please enter',
      birthStepLine2: 'your birth date',
      genderStep: 'Select your gender',
      genderStepLine1: 'Finally,',
      genderStepLine2: 'select your gender',
      continue: 'Continue',
      start: 'Start',
      emailPlaceholder: 'abc@nextvinetech.com',
      emailRequired: 'Please enter your email',
      invalidEmail: 'Invalid email format',
      emailExists: 'This email is already registered',
      emailCheckError: 'Error checking email',
      passwordRequired: 'Please enter your password',
      passwordTooShort: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      nameRequired: 'Please enter your name',
      yearPlaceholder: 'Year',
      monthPlaceholder: 'Month',
      dayPlaceholder: 'Day',
      male: 'Male',
      female: 'Female',
      signupFailed: 'Sign up failed.',
      stepTitleEmail: 'Email',
      stepTitlePassword: 'Password',
      stepTitleName: 'Name',
      stepTitleBirth: 'Birth Date',
      stepTitleGender: 'Gender',
      stepTitleDefault: 'Sign Up',
    },
    // Side Menu
    sideMenu: {
      regularMember: 'Regular Member',
      accountInfo: 'Account Info',
      subscriptionSettings: 'Subscription',
      settings: 'Settings',
      customerService: 'Customer Service',
      logout: 'Logout',
      relatedServices: 'Related Services',
      gymWork: 'GymWork',
      spineHealth: 'SpineHealth',
      smartShoes: 'SmartShoes',
      wristDoctor: 'WristDoctor',
    },
    // My Page
    morePage: {
      user: 'User',
      browseApps: 'Browse Related Apps',
      gymWork: 'GymWork',
      spineHealth: 'SpineHealth',
      smartShoes: 'SmartShoes',
      wristDoctor: 'WristDoctor',
      imageOnly: 'Only image files can be uploaded.',
      imageSizeLimit: 'Image size must be 5MB or less.',
      profileImageChanged: 'Profile image has been changed.',
      uploadFailed: 'Failed to upload image. Please try again.',
    },
    // Measurement List
    measurementList: {
      title: 'Measurement List',
      newest: 'Newest',
      oldest: 'Oldest',
      upperBack: 'Upper Back',
      lumbar: 'Lumbar',
      noData: 'No measurement data',
      loading: 'Loading...',
      camera2D: '2D Camera Scan',
      video3D: '3D Video Scan',
      scoliometerMeasure: 'Scoliometer Scan',
    },
    // Report
    report: {
      spineBalanceAnalysis: 'Spine Balance Analysis',
      severityAnalysis: 'Severity Analysis',
      curvePattern: 'Curve Pattern',
      doctorOpinion: "Doctor's Opinion (Final Assessment)",
      proximalThoracic: 'Proximal Thoracic',
      mainThoracic: 'Main Thoracic',
      secondThoracic: 'Secondary Thoracic',
      lumbar: 'Lumbar',
      pelvicTilt: 'Pelvic Tilt',
      shoulderTilt: 'Shoulder Tilt',
      myMeasurement: 'My Measurement',
      populationAvg: 'Population Average',
      koreaAvg: 'Korea Scoliosis Avg',
      chartDescription: 'Compare your spine balance (green) with population average (gray)',
      triangleChartDescription: 'Compare your scoliosis angle (mint) with Korean average (gray dashed, 18°). Closer to center is better.',
      mild: 'Mild',
      moderate: 'Moderate',
      severe: 'Severe',
      mildRange: 'Mild (10-24°)',
      moderateRange: 'Moderate (25-40°)',
      severeRange: 'Severe (>40°)',
      mainCurveAngle: 'The main curve angle is {angle}°, classified as {severity}',
      noDataTitle: 'No measurement data',
      noDataDesc: 'Please perform a spine measurement first',
      doubleThoracic: 'Double Thoracic Curve',
      doubleThoracicDesc: 'Two curves in the upper and middle back with a relatively straight lower back',
      thoracolumbarSCurve: 'Thoracolumbar Curve (S-Shape)',
      thoracolumbarSCurveDesc: 'S-shaped curve with opposing curves in the back and lumbar regions',
      singleThoracic: 'Single Thoracic Curve',
      singleThoracicDesc: 'A single curve primarily in the upper back region',
      lumbarCurve: 'Lumbar Curve',
      lumbarCurveDesc: 'A curve primarily in the lower back region',
      normalRange: 'Normal Range',
      normalRangeDesc: 'Your spine is within normal range. Regular maintenance is recommended',
      complexCurve: 'Complex Curve',
      complexCurveDesc: 'Multiple curves present in various regions',
      riskAssessment: 'Risk Assessment',
      normal: 'Normal',
      mildRisk: 'Mild Risk',
      moderateRisk: 'Moderate Risk',
      severeRisk: 'Severe Risk',
      prognosis: 'Prognosis',
      braceRecommendation: 'Brace Recommendation',
      postureErgonomics: 'Posture & Ergonomics',
      recommendedExercises: 'Recommended Exercises',
      prognosisUnder20: 'Annual check-up recommended. Be mindful of your posture and maintain good posture in daily life.',
      prognosis20to40: 'Re-evaluation every 6 months recommended. Consider consulting a specialist.',
      prognosisOver40: 'Prompt consultation with an orthopedic specialist is recommended.',
      normalPrognosis: 'Your spine is in good condition. Maintain health with regular posture checks and exercise.',
      normalBrace: 'No brace required.',
      normalPosture: 'Maintain good posture habits and avoid prolonged static positions.',
      mildPrognosis: 'Mild curvature present but progression can be prevented with proper management.',
      mildBrace: 'No brace required, but regular check-ups are recommended.',
      mildPosture: 'Maintain good posture and consistently perform core strengthening exercises.',
      moderatePrognosis: 'Curvature may gradually progress, requiring ongoing management.',
      moderateBrace: 'Wear a TLSO brace for 18-20 hours daily for corrective effect.',
      moderatePosture: 'Maintain proper posture when sitting or standing. Use a chair with lumbar support.',
      severePrognosis: 'Specialist consultation required. Surgical treatment may be considered.',
      severeBrace: 'Consult a specialist for appropriate brace prescription.',
      severePosture: 'Avoid strenuous activities and perform rehabilitation exercises under professional guidance.',
      exercise1Mild: 'Core Strengthening: Plank',
      exercise1MildDur: 'Hold 30-60 sec, 3 sets',
      exercise2Mild: 'Stretching: Cat-Cow Pose',
      exercise2MildDur: '10 reps, 2 sets',
      exercise3Mild: 'Balance: Bird Dog',
      exercise3MildDur: '10 reps each side, 2 sets',
      exercise1Moderate: 'Gentle Stretching: Child Pose',
      exercise1ModerateDur: 'Hold 30 sec, 5 times',
      exercise2Moderate: 'Breathing: Diaphragmatic Breathing',
      exercise2ModerateDur: '5 minutes slowly',
      exercise3Moderate: 'Light Walking',
      exercise3ModerateDur: '20-30 min on flat ground',
      exercise1Severe: 'Rehabilitation with Professional Guidance',
      exercise1SevereDur: 'Consult physical therapist',
      exercise2Severe: 'Aquatic Exercise',
      exercise2SevereDur: 'As recommended by specialist',
      exercise3Severe: 'Breathing Exercises',
      exercise3SevereDur: '10 minutes daily',
      followUpAppointment: 'Schedule Follow-up',
      preparingTitle: 'Coming Soon',
      preparingDesc: 'The follow-up appointment\nfeature is being prepared',
      emptyStateMessage: 'Perform a spine checkup\nto view your analysis report',
    },
    // Subscription
    subscription: {
      title: 'Subscription Settings',
      premiumSubscription: 'Premium Subscription',
      feature1: 'AI-powered precise spine analysis',
      feature2: 'Unlimited measurements and analysis reports',
      feature3: 'Expert medical opinions and advice',
      feature4: 'Personalized exercise recommendations and correction guides',
      monthlyPrice: '${price}/month',
      subscribed: 'Subscribed',
      cancelSubscription: 'Cancel Subscription',
      subscribe: 'Subscribe',
      nextBillingDate: 'Next billing date: {date}',
      membershipNotes: 'Membership Notes',
      purchaseGuide: 'Purchase Guide',
      refundGuide: 'Refund Guide',
      note1: 'The payment includes VAT',
      note2: 'The membership fee will be automatically charged monthly on the billing date using your registered payment method.',
      note3: 'You can cancel your membership at any time and continue using it until the expiration date',
      cancelConfirmTitle: 'Cancel Subscription',
      cancelConfirmMessage: 'Are you sure you want to cancel your subscription?\nYou can still use the service until the expiration date.',
      cancel: 'Cancel',
      confirm: 'Confirm',
      notice: 'Notice',
      preparing: 'Coming soon.',
      subscribeSuccess: 'Subscription completed.',
      subscribeFailed: 'Subscription failed.',
      cancelSuccess: 'Subscription cancelled.',
      cancelFailed: 'Failed to cancel subscription.',
      // Plan name translations
      planNames: {
        '베이직': 'Basic',
        '스탠다드': 'Standard',
        '프리미엄': 'Premium',
      },
    },
  }
};

const LANGUAGE_STORAGE_KEY = 'scolioscan_language';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // localStorage에서 저장된 언어 설정 불러오기
    const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return savedLanguage || 'ko';
  });

  // 언어 변경 시 localStorage에 저장
  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  // 번역 텍스트 가져오기
  const t = useCallback((key) => {
    const keys = key.split('.');
    let result = translations[language];

    for (const k of keys) {
      if (result && result[k] !== undefined) {
        result = result[k];
      } else {
        // 키를 찾을 수 없으면 한국어로 폴백
        result = translations['ko'];
        for (const fallbackKey of keys) {
          if (result && result[fallbackKey] !== undefined) {
            result = result[fallbackKey];
          } else {
            return key; // 키 자체를 반환
          }
        }
        break;
      }
    }

    return result;
  }, [language]);

  const value = {
    language,
    setLanguage,
    t,
    isKorean: language === 'ko',
    isEnglish: language === 'en',
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
