import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardWrap: {
    flex: 1,
  },
  screen: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    alignItems: 'flex-start',
    height: 56,
    justifyContent: 'center',
  },
  ㅍ: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  content: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 24,
  },
  title: {
    color: '#404552',
    fontFamily: 'PretendardVariable',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 36,
    marginBottom: 36,
  },
  helperText: {
    color: '#7A8190',
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  passwordRules: {
    marginTop: 10,
    gap: 8,
  },
  passwordRuleRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  passwordRuleIcon: {
    marginRight: 8,
  },
  passwordRuleText: {
    color: '#8D95A3',
    fontFamily: 'PretendardVariable',
    fontSize: 13,
    lineHeight: 18,
  },
  passwordRuleTextActive: {
    color: '#2C9696',
  },
  birthdayWrap: {
    marginTop: 20,
  },
  birthdayRow: {
    flexDirection: 'row',
    gap: 8,
  },
  birthdayYearBox: {
    flex: 1.2,
  },
  birthdayMonthBox: {
    flex: 1,
  },
  birthdayDayBox: {
    flex: 1,
  },
  birthdayInputBox: {
    backgroundColor: '#F7F7F8',
    borderColor: '#DADADC',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  birthdayInput: {
    color: '#292929',
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '500',
    paddingVertical: 0,
  },
  carrierWrap: {
    marginTop: 8,
  },
  carrierGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap : 10
  },
  carrierButton: {
    alignItems: 'center',
    backgroundColor: '#F3F4F7',
    borderColor: '#E1E5EC',
    borderRadius: 6,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    width: '31.5%',
  },
  carrierButtonActive: {
    backgroundColor: '#EAF6F5',
    borderColor: '#69A9A7',
  },
  carrierButtonText: {
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '500',
    textAlign: 'center',
  },
  carrierButtonTextActive: {
    color: '#4F9A97',
  },
  phoneWrap: {
    marginTop: 18,
  },
  phoneFieldBox: {
    alignItems: 'center',
    backgroundColor: '#F7F7F8',
    borderColor: '#DADADC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: 18,
  },
  phoneInput: {
    color: '#292929',
    flex: 1,
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '500',
    minHeight: 56,
    paddingVertical: 0,
    width: '100%',
  },
  phoneHelperText: {
    color: '#8D95A3',
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
  },
  messageWrap: {
    flex: 1,
    paddingTop: 0,
  },
  messageTitle: {
    color: '#3B4049',
    fontFamily: 'PretendardVariable',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 38,
    marginBottom: 22,
  },
  messageGuideList: {
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  messageGuideRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  messageGuideNumber: {
    alignItems: 'center',
    backgroundColor: '#4F5562',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    marginTop: 1,
    width: 22,
  },
  messageGuideNumberText: {
    color: '#FFFFFF',
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  messageGuideText: {
    color: '#000000',
    flex: 1,
    fontFamily: 'PretendardVariable',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 20,
  },
  messagePreviewWrap: {
    alignItems: 'center',
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  messagePreviewImage: {
    height: 186,
    width: '100%',
  },
  messageFootnote: {
    color: '#97A2B9',
    fontFamily: 'PretendardVariable',
    fontSize: 10,
    lineHeight: 16,
    marginTop: 10,
    textAlign: 'center',
  },
  completeWrap: {
    flex: 1,
    paddingTop: 24,
  },
  completeTitle: {
    color: '#404552',
    fontFamily: 'PretendardVariable',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 34,
  },
  genderWrap: {
    marginTop: 8,
  },
  genderRow: {
    flexDirection: 'row',
    gap: 10,
  },
  genderButton: {
    alignItems: 'center',
    backgroundColor: '#F3F4F7',
    borderColor: '#E1E5EC',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    height: 58,
    justifyContent: 'center',
  },
  genderButtonActive: {
    backgroundColor: '#EAF6F5',
    borderColor: '#69A9A7',
  },
  genderText: {
    color: '#7A8190',
    fontFamily: 'PretendardVariable',
    fontSize: 16,
    fontWeight: '600',
  },
  genderTextActive: {
    color: '#4F9A97',
  },
  footer: {
    paddingBottom: 16,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 6,
    height: 48,
    justifyContent: 'center',
    width: '100%',
  },
  primaryButtonActive: {
    backgroundColor: '#5F9F9D',
  },
  primaryButtonDisabled: {
    backgroundColor: '#CBD5D8',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontFamily: 'PretendardVariable',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
  },
  pressed: {
    opacity: 0.9,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(17, 24, 39, 0.35)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    maxWidth: 320,
    paddingHorizontal: 20,
    paddingVertical: 20,
    width: '100%',
  },
  modalTitle: {
    color: '#1F2937',
    fontFamily: 'PretendardVariable',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalMessage: {
    color: '#4B5563',
    fontFamily: 'PretendardVariable',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  modalButton: {
    alignItems: 'center',
    backgroundColor: '#5F9F9D',
    borderRadius: 6,
    height: 42,
    justifyContent: 'center',
    marginTop: 18,
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontFamily: 'PretendardVariable',
    fontSize: 15,
    fontWeight: '600',
  },
});
