import { StyleSheet } from 'react-native';
import { Colors } from '@/src/constants/theme';
import { textFont } from '@/src/constants/fonts';
const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: Colors.gray[25],
	},
	absoluteImage: {
		position: "absolute",
		top: 0,
		right: 0,
		width: 20,
		height: 20,
	},
	box: {
		width: 24,
		height: 24,
	},
	button: {
		alignItems: "center",
		backgroundColor: "#2B9696",
		borderRadius: 6,
		paddingVertical: 13,
	},
	buttonDisabled: {
		backgroundColor: "#C9D0DB",
	},
	buttonColumn: {
		flex: 1,
		alignItems: "center",
		backgroundColor: "#EDFCFC",
		borderColor: "#7AD7D4",
		borderRadius: 8,
		borderWidth: 1,
		paddingVertical: 14,
		marginRight: 8,
	},
	buttonColumn2: {
		flex: 1,
		alignItems: "center",
		backgroundColor: "#F9F9FB",
		borderColor: "#ECEEF2",
		borderRadius: 8,
		borderWidth: 1,
		paddingVertical: 14,
	},
	buttonColumn3: {
		flex: 1,
		alignItems: "center",
		backgroundColor: "#F9F9FB",
		borderColor: "#ECEEF2",
		borderRadius: 8,
		borderWidth: 1,
		paddingVertical: 14,
		marginRight: 8,
	},
	buttonColumn4: {
		alignItems: "center",
		backgroundColor: "#F2F4F6",
		borderColor: "#D3D8E2",
		borderRadius: 8,
		borderWidth: 1,
		height: 84,
		justifyContent: "center",
		width: 84,
	},
	column: {
		backgroundColor: Colors.primary["white"],
		borderRadius: 12,
		padding: 12,
		marginBottom: 8,
		marginHorizontal: 16,
		shadowColor: "#00000008",
		shadowOpacity: 1,
		shadowOffset: {
		    width: 0,
		    height: 0
		},
		shadowRadius: 16,
		elevation: 16,
	},
	column2: {
		marginBottom: 8,
	},
	image: {
		width: 24,
		height: 24,
	},
	image2: {
		borderRadius: 8,
		width: 24,
		height: 24,
		marginBottom: 10,
	},
	image3: {
		borderRadius: 8,
		width: 24,
		height: 24,
		marginBottom: 8,
	},
	screenshotImage: {
		borderRadius: 8,
		height: "100%",
		width: "100%",
	},
	screenshotPreview: {
		borderRadius: 8,
		height: 84,
		overflow: "hidden",
		position: "relative",
		width: 84,
	},
	screenshotRemoveButton: {
		alignItems: "center",
		backgroundColor: "rgba(0, 0, 0, 0.55)",
		borderRadius: 10,
		height: 20,
		justifyContent: "center",
		position: "absolute",
		right: 4,
		top: 4,
		width: 20,
	},
	input: {
		...textFont,
		color: "#2B9696",
		fontSize: 13,
		marginBottom: 16,
		marginHorizontal: 16,
		backgroundColor: "#EDFCFC",
		borderRadius: 8,
		paddingVertical: 8,
		paddingHorizontal: 12,
	},
	input2: {
		...textFont,
		color: Colors.primary["black"],
		fontSize: 15,
		backgroundColor: "#F2F4F6",
		borderColor: "#D3D8E2",
		borderRadius: 6,
		borderWidth: 1,
		padding: 16,
		textDecorationLine: "none",
	},
	row: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		backgroundColor: "#F9F9FB",
		padding: 20,
	},
	header: {
		alignItems: "center",
		backgroundColor: "#F9F9FB",
		flexDirection: "row",
		justifyContent: "space-between",
		padding: 20,
	},
	headerBackButton: {
		alignItems: "center",
		height: 24,
		justifyContent: "center",
		width: 24,
	},
	headerTitle: {
		...textFont,
		color: "#2B2E35",
		fontSize: 18,
		fontWeight: "700",
		lineHeight: 25,
	},
	headerSide: {
		height: 24,
		width: 24,
	},
	row2: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 8,
	},
	row3: {
		flexDirection: "row",
		alignItems: "center",
	},
	row4: {
		alignSelf: "flex-start",
		flexDirection: "row",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 8,
		paddingVertical: 10,
	},
	scrollView: {
		flex: 1,
		backgroundColor: "#F9F9FB",
		shadowColor: "#00000008",
		shadowOpacity: 1,
		shadowOffset: {
		    width: 0,
		    height: 0
		},
		shadowRadius: 16,
		elevation: 16,
	},
	scrollContent: {
		paddingBottom: 16,
	},
	infoBox: {
		backgroundColor: Colors.mint[25],
		borderRadius: 8,
		marginBottom: 16,
		marginHorizontal: 16,
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	infoText: {
		...textFont,
		color: Colors.primary[500],
		fontSize: 13,
		fontWeight: "500",
		lineHeight: 18,
	},
	text: {
		...textFont,
		color: "#2B2E35",
		fontSize: 18,
		fontWeight: "bold",
	},
	text2: {
		...textFont,
		color: "#2B2E35",
		fontSize: 15,
		marginBottom: 8,
		marginLeft: 4,
	},
	text3: {
		...textFont,
		color: "#000000",
		fontSize: 10,
	},
	text4: {
		...textFont,
		color: "#B5BDCE",
		fontSize: 15,
		lineHeight: 20,
		minHeight: 188,
	},
	messageInput: {
		...textFont,
		backgroundColor: "#F2F4F6",
		borderColor: "#D3D8E2",
		borderRadius: 6,
		borderWidth: 1,
		color: Colors.primary["black"],
		fontSize: 15,
		lineHeight: 20,
		minHeight: 220,
		paddingHorizontal: 16,
		paddingTop: 14,
		textDecorationLine: "none",
	},
	text5: {
		color: "#2B2E35",
		marginBottom: 8,
		marginLeft: 4,
	},
	text6: {
		color: "#000000",
		marginBottom: 2,
		marginLeft: 8,
	},
	text7: {
		...textFont,
		color: "#646F85",
		fontSize: 12,
	},
	text8: {
		...textFont,
		color: "#FFFFFF",
		fontSize: 16,
	},
	view: {
		backgroundColor: "#F2F4F6",
		borderColor: "#D3D8E2",
		borderRadius: 6,
		borderWidth: 1,
		paddingTop: 14,
		paddingLeft: 16,
	},
	view2: {
		backgroundColor: "#F9F9FB",
		padding: 16,
	},
	typeButton: {
		flex: 1,
		alignItems: "center",
		borderRadius: 8,
		borderWidth: 1,
		paddingVertical: 14,
	},
	typeButtonGap: {
		marginRight: 8,
	},
	typeButtonActive: {
		backgroundColor: "#EDFCFC",
		borderColor: "#7AD7D4",
	},
	typeButtonInactive: {
		backgroundColor: "#F9F9FB",
		borderColor: "#ECEEF2",
	},
	fixedFooter: {
		backgroundColor: "#F9F9FB",
		paddingHorizontal: 16,
		paddingTop: 12,
	},
});

export default styles;
