import { Colors } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    backgroundColor: Colors.gray[25],
    flex: 1,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 80,
    paddingHorizontal: 16,
  },
  backButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  headerTitle: {
    color: '#20242C',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  headerSide: {
    width: 36,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 0,
  },
  sectionTitle: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 12,
  },
  accountSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.03,
    shadowRadius: 14,
    elevation: 1,
  },
  sectionSpacing: {
    marginTop: 20,
  },
  loginSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.03,
    shadowRadius: 14,
    elevation: 1,
  },
  loginMethodRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 46,
  },
  loginMethodIcon: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  loginMethodContent: {
    flex: 1,
  },
  loginMethodTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  loginMethodTitle: {
    color: Colors.gray[800],
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
  },
  loginMethodEmail: {
    color: Colors.gray[500],
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 15,
    marginTop: 3,
  },
  infoBadge: {
    alignItems: 'center',
    backgroundColor: Colors.mint[25],
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  infoBadgeText: {
    color: Colors.mint[600],
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 14,
  },
  deviceSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.03,
    shadowRadius: 14,
    elevation: 1,
  },
  deviceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
  },
  deviceContent: {
    flex: 1,
    paddingRight: 12,
  },
  deviceTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  deviceTitle: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  deviceMeta: {
    color: Colors.gray[500],
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 14,
    marginTop: 3,
  },
  activeBadge: {
    alignItems: 'center',
    backgroundColor: Colors.mint[25],
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  activeBadgeText: {
    color: Colors.mint[600],
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 14,
  },
  deviceLogoutText: {
    color: Colors.gray[400],
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  actionArea: {
    marginTop: 20,
    paddingBottom: 12,
    paddingHorizontal: 0,
  },
  actionLinkRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
  },
  actionLinkText: {
    color: Colors.gray[500],
    fontSize: 14,
    fontWeight: '500',
    lineHeight : 20
  },
  actionDivider: {
    backgroundColor: '#D8DDE5',
    height: 11,
    marginHorizontal: 14,
    width: 1,
  },
  saveButton: {
    alignSelf: 'stretch',
    width: '100%',
    height : 48
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  fieldGroup: {
    marginBottom: 22,
  },
  fieldLabel: {
    color: Colors.gray[800],
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 8,
  },
  inputWrap: {
    alignItems: 'center',
    backgroundColor: '#F3F4F7',
    borderColor: '#D4D9E2',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  input: {
    color: '#2B2F36',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    padding: 0,
  },
  birthRow: {
    flexDirection: 'row',
    gap: 10,
  },
  birthInputWrap: {
    alignItems: 'center',
    backgroundColor: '#F0F2F6',
    borderColor: '#E1E5EB',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  birthInput: {
    color: '#2B2F36',
    fontSize: 13,
    fontWeight: '700',
    padding: 0,
    textAlign: 'center',
    width: '100%',
  },
  birthInputText: {
    color: '#2B2F36',
    fontSize: 13,
    fontWeight: '700',
  },
  genderRow: {
    flexDirection: 'row',
    gap: 10,
  },
  genderOption: {
    alignItems: 'center',
    backgroundColor: '#F0F2F6',
    borderColor: '#F0F2F6',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  genderOptionActive: {
    backgroundColor: '#F0FBFB',
    borderColor: '#5EAAA8',
  },
  genderText: {
    color: '#A1A9B3',
    fontSize: 13,
    fontWeight: '800',
  },
  genderTextActive: {
    color: '#5EAAA8',
  },
  withdrawModalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  withdrawModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 0,
    width: '100%',
    maxWidth: 360,
  },
  withdrawModalTitle: {
    color: '#25272D',
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 20,
    marginLeft: 8,
    marginBottom: 4,
  },
  withdrawModalDescription: {
    color: '#657085',
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 14,
    marginLeft: 8,
    marginBottom: 16,
  },
  withdrawDeleteBox: {
    alignSelf: 'stretch',
    backgroundColor: '#F3F4F7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 15,
  },
  withdrawDeleteTitle: {
    color: '#657085',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    marginBottom: 4,
  },
  withdrawDeleteText: {
    color: '#3B4049',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    paddingLeft: 19,
  },
  withdrawConfirmText: {
    color: '#25272D',
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 20,
    marginLeft: 8,
    marginBottom: 9,
  },
  withdrawPasswordWrap: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#F3F4F7',
    borderColor: '#D4D9E2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 46,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  withdrawPasswordInput: {
    color: '#25272D',
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    padding: 0,
  },
  withdrawErrorText: {
    color: '#E5484D',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
    marginTop: -8,
    marginBottom: 12,
    marginLeft: 8,
  },
  withdrawButtonRow: {
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 16,
  },
  withdrawCancelButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#F3F4F7',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  withdrawCancelText: {
    color: '#25272D',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  withdrawConfirmButton: {
    alignItems: 'center',
    backgroundColor: '#D4D9E2',
    borderRadius: 6,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  withdrawConfirmButtonActive: {
    backgroundColor: '#ff4b3c',
  },
  withdrawConfirmButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  withdrawCompleteCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    maxWidth: 320,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 16,
    width: '100%',
  },
  withdrawCompleteTitle: {
    color: '#25272D',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    marginBottom: 20,
    textAlign: 'center',
  },
  withdrawCompleteButton: {
    alignItems: 'center',
    backgroundColor: '#5EAAA8',
    borderRadius: 6,
    height: 44,
    justifyContent: 'center',
    width: '100%',
  },
  withdrawCompleteButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  fixedFooter: {
    backgroundColor: Colors.gray[25],
    // borderTopColor: Colors.gray[25],

    paddingHorizontal: 16,
  
  },
});

export default styles;
