import { Colors } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    backgroundColor: '#F6F7F9',
    flex: 1,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 80,
    paddingHorizontal: 16,
  },
  backButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  headerTitle: {
    color: '#20242C',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  headerSide: {
    width: 36,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 0,
  },
  sectionTitle: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 12,
  },
  accountSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.03,
    shadowRadius: 14,
    elevation: 1,
  },
  actionArea: {
    marginTop: 20,
    paddingBottom: 12,
    paddingHorizontal: 0,
  },
  actionLinkRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
  },
  actionLinkText: {
    color: Colors.gray[500],
    fontSize: 14,
    fontWeight: '500',
    lineHeight : 20
  },
  actionDivider: {
    backgroundColor: '#D8DDE5',
    height: 11,
    marginHorizontal: 14,
    width: 1,
  },
  saveButton: {
    alignSelf: 'stretch',
    width: '100%',
    height : 48
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  fieldGroup: {
    marginBottom: 22,
  },
  fieldLabel: {
    color: Colors.gray[800],
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 8,
  },
  inputWrap: {
    alignItems: 'center',
    backgroundColor: '#F3F4F7',
    borderColor: '#D4D9E2',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  input: {
    color: '#2B2F36',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    padding: 0,
  },
  birthRow: {
    flexDirection: 'row',
    gap: 10,
  },
  birthInputWrap: {
    alignItems: 'center',
    backgroundColor: '#F0F2F6',
    borderColor: '#E1E5EB',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  birthInput: {
    color: '#2B2F36',
    fontSize: 13,
    fontWeight: '700',
    padding: 0,
    textAlign: 'center',
    width: '100%',
  },
  birthInputText: {
    color: '#2B2F36',
    fontSize: 13,
    fontWeight: '700',
  },
  genderRow: {
    flexDirection: 'row',
    gap: 10,
  },
  genderOption: {
    alignItems: 'center',
    backgroundColor: '#F0F2F6',
    borderColor: '#F0F2F6',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  genderOptionActive: {
    backgroundColor: '#F0FBFB',
    borderColor: '#5EAAA8',
  },
  genderText: {
    color: '#A1A9B3',
    fontSize: 13,
    fontWeight: '800',
  },
  genderTextActive: {
    color: '#5EAAA8',
  },
  withdrawModalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  withdrawModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 12,
    width: '100%',
    maxWidth: 360,
  },
  withdrawModalTitle: {
    color: Colors.gray[900],
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
    marginBottom: 4,
  },
  withdrawModalDescription: {
    color: Colors.gray[500],
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
    marginBottom: 12,
  },
  withdrawDeleteBox: {
    backgroundColor: '#F1F3F7',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 14,
  },
  withdrawDeleteTitle: {
    color: Colors.gray[600],
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginBottom: 4,
  },
  withdrawDeleteText: {
    color: Colors.gray[800],
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 21,
  },
  withdrawConfirmText: {
    color: Colors.gray[900],
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    marginBottom: 12,
  },
  withdrawPasswordWrap: {
    alignItems: 'center',
    backgroundColor: '#F7F8FB',
    borderColor: '#D6DCE6',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  withdrawPasswordInput: {
    color: Colors.gray[800],
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    padding: 0,
  },
  withdrawButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  withdrawCancelButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#EEF1F5',
    borderRadius: 6,
    borderWidth: 1,
    flex: 1,
    height: 46,
    justifyContent: 'center',
  },
  withdrawCancelText: {
    color: Colors.gray[900],
    fontSize: 14,
    fontWeight: '600',
  },
  withdrawConfirmButton: {
    alignItems: 'center',
    backgroundColor: '#D0D6E1',
    borderRadius: 6,
    flex: 1,
    height: 46,
    justifyContent: 'center',
  },
  withdrawConfirmButtonActive: {
    backgroundColor: '#5EAAA8',
  },
  withdrawConfirmButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});

export default styles;
