import { StyleSheet } from 'react-native';
import { Colors } from '@/src/constants/theme';

const styles = StyleSheet.create({
  screen: {
    backgroundColor: Colors.gray[25],
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  profileCard: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 68,
    paddingHorizontal: 2,
    paddingVertical: 10,
  },
  avatar: {
    alignItems: 'center',
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  profileText: {
    flex: 1,
    marginLeft: 12,
  },
  nameLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  profileName: {
    color: '#20242C',
    fontSize: 14,
    fontWeight: '700',
  },
  proBadge: {
    backgroundColor: '#FFF4DC',
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  proBadgeText: {
    color: '#F5A623',
    fontSize: 9,
    fontWeight: '700',
  },
    profileEmail: {
    color: Colors.gray[400],
    fontSize: 14,
    fontWeight : 400,
    lineHeight : 20,
  },
  accountManagePill: {
    alignItems: 'center',
    backgroundColor: '#F1F3F6',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 2,
    marginLeft: 12,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  accountManageText: {
    color: Colors.gray[500],
    fontSize: 10,
    fontWeight: '400',
    lineHeight : 14,
  },
  subscriptionTitle: {
    color: '#222832',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
    marginTop: 8,
    paddingHorizontal: 2,
  },
  subscriptionCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  subscriptionLeft: {
    gap: 8,
  },
  subscriptionLabel: {
    color: '#454B56',
    fontSize: 14,
    fontWeight: '400',
    paddingBottom : 12,
    lineHeight : 20,
  },
  subscriptionStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  subscriptionText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '400',
    lineHeight : 20,
  },
  linkText: {
    color: Colors.primary[500],
    fontSize: 12,
    fontWeight: '400',
    lineHeight : 16,
  },
  section: {
    marginTop: 20,
  },
  sectionTitle: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 12,
    marginLeft: 4,
    lineHeight : 20,
  },
  sectionBody: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 42,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 10,
  },
  rowPressed: {
    backgroundColor: '#F7FAFB',
  },
  rowText: {
    flex: 1,
    paddingRight: 12,
  },
  rowTitle: {
    color: '#24272C',
    fontSize: 16,
    fontWeight: '400',
    lineHeight : 22
  },
  rowDescription: {
    color: '#646F85',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  rowMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  rowValue: {
    color: '#96A2B9',
    fontSize: 12,
  },
  dangerText: {
    color: '#E15B58',
  },
  timeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    justifyContent: 'flex-start',
    minHeight: 30,
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 20,
  },
  timeField: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  timeLabel: {
    color: '#646F85',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
  },
  timePill: {
    alignItems: 'center',
    backgroundColor: '#F2F4F6',
    borderColor: '#D3D8E2',
    borderRadius: 8,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 10,
    width: 90,
  },
  timePillPressed: {
    backgroundColor: Colors.gray[75],
  },
  timePillText: {
    color: '#24272C',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    includeFontPadding: false,
  },
  timeSeparator: {
    color: '#646F85',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 18,
  },
  timeDropdownOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.32)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  timeDropdownCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    maxHeight: 420,
    maxWidth: 320,
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 12,
    width: '100%',
  },
  timeDropdownTitle: {
    color: Colors.gray[900],
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  timeDropdownList: {
    maxHeight: 340,
  },
  timeDropdownOption: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  timeDropdownOptionSelected: {
    backgroundColor: Colors.mint[25],
  },
  timeDropdownOptionDisabled: {
    opacity: 0.35,
  },
  timeDropdownOptionText: {
    color: Colors.gray[700],
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  timeDropdownOptionTextSelected: {
    color: Colors.mint[600],
    fontWeight: '700',
  },
  timeDropdownOptionTextDisabled: {
    color: Colors.gray[400],
  },
});

export default styles;
