import { StyleSheet } from 'react-native';
import { textFont } from '@/src/constants/fonts';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#000',
  },
  permissionScreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  permissionContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  permissionTitle: {
    ...textFont,
    color: '#1F2A2A',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
    textAlign: 'center',
  },
  permissionMessage: {
    ...textFont,
    marginTop: 10,
    color: '#667077',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    textAlign: 'center',
  },
  permissionButton: {
    marginTop: 24,
    minWidth: 150,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#2C9696',
    paddingHorizontal: 20,
  },
  permissionButtonText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  cameraStage: {
    flex: 1,
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  topBar: {
    minHeight: 56,
    paddingHorizontal: 40,
    paddingTop: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  topText: {
    ...textFont,
    color: '#fff',
    fontSize: 15,

  },
  closeText: {
    ...textFont,
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  guideCard: {
    alignSelf: 'center',
    marginHorizontal: 20,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(12, 14, 18, 0.62)',
  },
  guideCardText: {
    ...textFont,
    color: '#fff',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  guideMetaRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guideMetaText: {
    ...textFont,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
  },
  bottomBar: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 34,
  },
  // 자동 촬영 조건을 만족했을 때 카메라 화면 중앙에 카운트다운 숫자를 띄우는 영역이다.
  countdownWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '42%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // 카메라 프리뷰 위에서도 숫자가 잘 보이도록 큰 글자와 그림자를 사용한다.
  countdownText: {
    ...textFont,
    color: '#fff',
    fontSize: 76,
    fontWeight: '800',
    lineHeight: 86,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.36)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
  },
  shutterButton: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  shutterButtonDisabled: {
    opacity: 0.6,
  },
  shutterInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 3,
    borderColor: '#d9d9d9',
    backgroundColor: '#fff',
  },
  outlineWrap: {
    position: 'absolute',
    pointerEvents: 'none',
  },
});
