import { StyleSheet } from 'react-native';
import { textFont } from '@/src/constants/fonts';
import { Colors } from '@/src/constants/theme';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#000',
  },
  permissionScreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  permissionContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  permissionTitle: {
    ...textFont,
    color: '#1F2A2A',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
    textAlign: 'center',
  },
  permissionMessage: {
    ...textFont,
    marginTop: 10,
    color: '#667077',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    textAlign: 'center',
  },
  permissionButton: {
    marginTop: 24,
    minWidth: 150,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#2C9696',
    paddingHorizontal: 20,
  },
  permissionButtonText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  cameraStage: {
    flex: 1,
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
  },
  safeArea: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
 topBar: {
  height: 116,
  paddingHorizontal: 20,
  paddingTop: 76,
  paddingBottom: 20,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-start',
  gap: 20,
  backgroundColor: Colors.primary['black'],
  zIndex: 10,
},
  topIconButton: {
  width: 24,
  height: 24,
  alignItems: 'center',
  justifyContent: 'center',
},
  closeText: {
    ...textFont,
    color: Colors.primary['white'],
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
    flexShrink: 1,
  },
  closeTextBold: {
  ...textFont,
  color: Colors.primary.white,
  fontSize: 13,
  fontWeight: '700',
  lineHeight: 18,
},
  guideCard: {
    alignSelf: 'center',
    marginHorizontal: 20,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(12, 14, 18, 0.62)',
  },
  guideCardText: {
    ...textFont,
    color: '#fff',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  guideMetaRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guideMetaText: {
    ...textFont,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
  },
  bottomBar: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 34,
  },
  shutterButton: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  shutterButtonDisabled: {
    opacity: 0.6,
  },
  shutterInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 3,
    borderColor: '#d9d9d9',
    backgroundColor: '#fff',
  },
  outlineWrap: {
    position: 'absolute',
    pointerEvents: 'none',
  },
  autoGuideChip: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 14,
    maxWidth: '94%',
    minHeight: 46,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  autoGuideChipError: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  autoGuideIcon: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  autoGuideInfoIcon: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#7AD7D4',
  },
  autoGuideSuccessIcon: {
    borderRadius: 5,
    backgroundColor: '#64FFC9',
  },
  autoGuideIconText: {
    ...textFont,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  autoGuideInfoIconText: {
    color: '#7AD7D4',
  },
  autoGuideSuccessIconText: {
    color: '#0F181A',
  },
  autoGuideChipText: {
    ...textFont,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'center',
  },
  autoGuideChipInfoText: {
    color: '#7AD7D4',
  },
  autoGuideChipSuccessText: {
    color: '#64FFC9',
  },
  captureCompleteBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
  },
  captureCompleteBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  captureCompleteTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
  },
  testLottieWrap: {
    position: 'absolute',
    zIndex: 25,
    pointerEvents: 'none',
  },
  testLottie: {
    width: '100%',
    height: '100%',
  },
  captureCompleteToast: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: '13%',
    zIndex: 30,
    minHeight: 48,
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  captureCompleteToastText: {
    ...textFont,
    color: '#20C99C',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
  },


});
