import { Colors } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';
import { textFont } from '@/src/constants/fonts';

const stageStyles = StyleSheet.create({
  stage: {
    backgroundColor: '#5E9E9F',
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    minHeight: 390,
    
  },
  // 측정 때 사용한 이미지 
  stageBackgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(28, 72, 74, 0.1)',
  },
  stageBackgroundPhoto: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    transform: [{ scale: 2.3 }],
  },
  spineLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arcMarker: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arcMarkerCenter: {
    backgroundColor: '#FFFFFF',
  },
  textLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  metric: {
    position: 'absolute',
    zIndex: 10,
  },
  metricLeft: {
    alignItems: 'flex-start',
  },
  metricRight: {
    alignItems: 'flex-end',
  },
  // 상부 흉추만곡, 주 흉추만곡, 요추 만곡 텍스트 스타일입니다.
  metricLabel: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '400',
    marginBottom: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.18)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    flexWrap: 'nowrap',
  },
  metricValue: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '600',
    letterSpacing: -0.6,
    textShadowColor: 'rgba(0, 0, 0, 0.14)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  metricValueSlot: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  digitFrame: {
    width: 24,
    height: 38,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  digitWheel: {
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  digitCell: {
    ...textFont,
    width: 24,
    height: 38,
    lineHeight: 38,
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
    fontVariant: ['tabular-nums'],
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '600',
    letterSpacing: -0.6,
    textShadowColor: 'rgba(0, 0, 0, 0.14)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  degree: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
    marginLeft: 1,
    paddingBottom: 5,
    textShadowColor: 'rgba(0, 0, 0, 0.14)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  errorText: {
    ...textFont,
    marginTop: 10,
    color: '#B04545',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyText: {
    ...textFont,
    marginTop: 10,
    color: '#65767B',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  retryButton: {
    alignSelf: 'center',
    marginTop: 10,
    backgroundColor: '#5E9E9F',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    ...textFont,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  spineBone: {
    position: 'absolute',
    overflow: 'visible',
  },
  spineRig: {
    position: 'relative',
  },
  spineImage: {
    resizeMode: 'contain',
  },
  stage2DHidden : {
    opacity : 0
  },
  stage3D: {
    backgroundColor: Colors.gray[900],
    borderRadius: 12,
  },
  stage3DModelSlot: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: '62%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  stage3DModelSlotHidden: {
    opacity: 0,
  },
  stage3DOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    elevation: 20,
  },
  stage3DMetricGroup: {
    position: 'absolute',
    left: 24,
    right: 28,
  },
  stage3DMetricBadge: {
    alignSelf: 'flex-start',
    minHeight: 18,
    justifyContent: 'center',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: Colors.gray[600],
  },
  stage3DMetricBadgeText: {
    ...textFont,
    color: Colors.primary.white,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '500',
    letterSpacing: 0,
  },
  stage3DMetricValues: {
    width: 118,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  stage3DMetricColumn: {
    width: 70,
    alignItems: 'flex-start',
  },
  stage3DMetricLabel: {
    ...textFont,
    color: Colors.primary.white,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '400',
    letterSpacing: 0,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  stage3DMetricValue: {
    ...textFont,
    color: Colors.primary.white,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    letterSpacing: 0,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
});

export default stageStyles;
